dbt_project:
  outputs:
    dev:
      type: duckdb
      path: reports/sources/jaffle_shop/dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
